import "./globals.css";
import { ErrorBoundary } from '@/components/ErrorBoundary';
import ThemeToggle from '@/components/ThemeToggle';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorBoundary>
          <header className="container mx-auto p-4 flex flex-col sm:flex-row sm:justify-between sm:items-center">
          <div className="flex items-center mb-4 sm:mb-0">
              <img src="/icon.jpg" alt="Icon" className="w-8 h-8 mr-2 rounded-full" />
              <span className="text-2xl font-bold">
                SpendinSight
              </span>
            </div>
            <ThemeToggle />
          </header>
          <main className="container mx-auto px-4">
            {children}
          </main>
        </ErrorBoundary>
      </body>
    </html>
  );
}
